### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by saoudrizwan** [indragiek/MarkdownTextView#12]
Causes ~50 memory leaks in its current state.

My code for reference:

lazy var composeTextView: MarkdownTextView = {

      // MarkdownTextView
        var attributes = MarkdownAttributes()
        attributes.defaultAttributes = [
            NSFontAttributeName: UIFont.systemFont(ofSize: constants.compose.textFontSize),
            NSForegroundColorAttributeName: constants.compose.textFontColor
        ]
        
        let textStorage = MarkdownTextStorage(attributes: attributes)
        do {
            textStorage.addHighlighter(try LinkHighlighter())
        } catch let error {
            fatalError("Error initializing LinkHighlighter: \(error)")
        }
        textStorage.addHighlighter(MarkdownStrikethroughHighlighter())
        textStorage.addHighlighter(MarkdownSuperscriptHighlighter())
        if let codeBlockAttributes = attributes.codeBlockAttributes {
            textStorage.addHighlighter(MarkdownFencedCodeHighlighter(attributes: codeBlockAttributes))
        }
        
        let textView = MarkdownTextView(frame: CGRect.zero, textStorage: textStorage)
        //textView.font = UIFont.systemFont(ofSize: constants.compose.textFontSize)
        //textView.textColor = constants.compose.textFontColor
        textView.backgroundColor = .clear
        //textView.textColor = constants.compose.textFontColor
        textView.font = UIFont.systemFont(ofSize: constants.compose.textFontSize)
        //textView.tintColor = constants.compose.textFontColor
        textView.textContainerInset = UIEdgeInsets(top: 5, left: 9, bottom: constants.compose.helpButton.padding, right: 9)
        
        textView.isEditable = true
        textView.isSelectable = true
        textView.isScrollEnabled = true
        textView.showsVerticalScrollIndicator = false
        textView.showsHorizontalScrollIndicator = false
        
        textView.keyboardAppearance = UIKeyboardAppearance.light
        
        // testing purposes
        textView.layer.borderWidth = constants.testingBorderWidth
        textView.layer.borderColor = UIColor.red.cgColor
        
        return textView
    }()

**Comment by indragiek** [comment]
Could you tell me which objects are leaking here?
