### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by nishkrishnan** [indragiek/MarkdownTextView#6]
I had to refactor a bunch of the code, to use with my project in Swift 2.0. You should make this compliant with that standard.

**Comment by penne12** [comment]
+1

**Comment by indragiek** [comment]
@penne12 @nishkrishnan Planning to release an updated version tomorrow with Swift 2 and Swift Package Manager support. Sorry for the delay!

**Comment by penne12** [comment]
Yay! Thanks! Cocoapod support, too, please?

**Comment by indragiek** [comment]
Version 1.0.0 has been tagged with Swift 2 support. No Swift Package Manager support because it doesn't work with iOS yet.

@penne12 There is already a podspec in the repo.

**Comment by penne12** [comment]
@indragiek awesomeness! Fastest I've ever seen a bug be fixed :grinning:. Didn't notice the pod spec, sorry.
